:schedule:
  expiration_date_worker:
    cron: '0 0 0 * * *'   # Runs once per day at midnight
    class: ExpirationDateWorker
  birthday_webhook_worker:
    cron: '0 0 13 * * *'   # Runs once per day at 1pm utc
    class: BirthdayWebhookWorker